remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Plataforma de Atendimento e Cursos Online (LMS)
description: Documentação completa do sistema de gerenciamento de aprendizado
show_downloads: true 